export default {
  BASE_URL: 'https://ratings-backend.herokuapp.com/',
  FETCH_LOGIN_API_URI: 'auth/login/',
  SOCIAL_LOGIN_URI: 'auth/socials/',
  REGISTER_API_URI: 'auth/register',
  USER_PROFILE: 'auth/getUserProfile',
  FETCH_RESTAURANTS: 'restaurants/fetchRestaurants/',
  CREATE_RESTAURANT: 'restaurants/createRestaurant',
  FETCH_RESTAURANT_DETAIL: 'restaurants/fetchRestaurant/',
  SUBMIT_RATINGS: 'reviews/submitReview',
  SUBMIT_OWNER_REPLY: 'reviews/updateOwnerReply',
  fetch_OWNED_RESTAURANTS: 'restaurants/fetchOwnedRestaurants',
  FETCH_OWNER_REVIEWS: 'reviews/getAllRestaurantReviews',
  FETCH_RESTAURANT_REVIEW: 'reviews/getRestaurantReviews/',
}
