name: code-check CI
on:
  push:
    branches-ignore: [master]

jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Lint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint

      - name: Unit tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
